#!/bin/bash

FUEL_ENV=$1

# Create directory for environment
mkdir -p ${FUEL_ENV}

# Prepare virtual environment

cd ${FUEL_ENV}
virtualenv ${FUEL_ENV}
. ${FUEL_ENV}/bin/activate

FUEL_FUNCTIONS="

dos.py start ${FUEL_ENV}

ngip() {
    NIC=\$(virsh net-info \$1_admin | grep 'Bridge:' | awk '{print \$2}')
    IP=\$(ifconfig \${NIC} | grep 'inet addr' | cut -d ':' -f 2 | cut -d ' ' -f 1)
    echo \$IP | sed 's/.1\$/.2/g'
}

ngopen() {
    NAILGUN_IP=\$(ngip \"${FUEL_ENV}\")
    xdg-open \"http://\${NAILGUN_IP}:8000/\"
}

fuelenv_deactivate() {
    deactivate
    dos.py destroy ${FUEL_ENV}
}

fssh() {
    SSH_EXPECT_LOGIN=\"spawn ssh root@\$(ngip \"${FUEL_ENV}\")
expect \"Password:\"
send \"r00tme\"
interact\"
    echo \"\$SSH_EXPECT_LOGIN\" | expect
}

fdockerctl() {
fssh dockerctl \"\$1\"
}

alias fuel=\"SERVER_ADDRESS=\$(ngip \${FUEL_ENV})\" fuel
alias fuel2=\"SERVER_ADDRESS=\$(ngip \${FUEL_ENV})\" fuel2"

echo "$FUEL_FUNCTIONS" >> ${FUEL_ENV}/bin/activate

# Install `fuel-devops`

pip install git+https://github.com/openstack/fuel-devops.git@2.9.12 --upgrade

# Checkout `fuel-web`

# git clone --depth 1 https://github.com/openstack/fuel-web

# Install `fuel-qa`

git clone --depth 1 https://github.com/openstack/fuel-qa
cd fuel-qa
pip install -r ./fuelweb_test/requirements.txt --upgrade
cd ..

# Build environment

FUEL_WORKSPACE=~/.fuelenv/
mkdir -p ${FUEL_WORKSPACE}
# FUEL_ISO_DIR=$FUEL_WORKSPACE/iso
# mkdir -p $FUEL_ISO_DIR
# export ISO_DIR=$FUEL_ISO_DIR

# ./fuel-qa/utils/jenkins/system_tests.sh -t test -j fuelweb_test -i $ISO_PATH -o --group=setup
./fuel-qa/utils/jenkins/system_tests.sh -t iso -j fuelweb_test -i $2 -r -V `pwd`/${FUEL_ENV}/ -w ${FUEL_WORKSPACE} -o --group=setup
./fuel-qa/utils/jenkins/system_tests.sh -e ${FUEL_ENV} -t test -j fuelweb_test -i $2 -V `pwd`/${FUEL_ENV}/ -w ${FUEL_WORKSPACE} -o --group=setup
